#!/usr/bin/env node
/*
 * tools-sync.js — generate README.md's "Maintaining the fleet" table from the tools
 * themselves.
 *
 * Run: node tools/tools-sync.js check
 * Prevents: this list drifting from the tools it describes
 * Reads: git ls-files -- tools, each tracked tools/*.js header and body, this repo's .github/workflows/*.yml, and README.md
 *
 * Every row is read out of the tool it describes: the one-line purpose from the first
 * sentence of its header, the command from its `Run:` line, and the failure it exists
 * to prevent from its `Prevents:` line. A `Reads:` line is required too and is not put
 * in the table - it is for the person checking a checker, who needs to know what it
 * opened before judging what it concluded, and that reader is in the source rather than
 * in the README. Nothing in the table is written by hand, so a
 * tool whose purpose changes and whose header follows drags the README with it, and
 * one whose header does not follow fails this check instead of quietly publishing a
 * stale sentence.
 *
 * The cadence column is derived the same way, from `.github/workflows/*.yml`: a tool
 * named in a workflow gets that workflow's triggers, and a tool named in none is
 * reported as manual. That column is the reason this table is worth generating rather
 * than writing. On 2026-09-23 it read 14 of 19 manual, and the manual group held every
 * checker that catches a whole-fleet failure — a lab serving a stale build, a lab live
 * with no card, branch protection changing under everyone. Written by hand, that
 * proportion would have been rounded off to "run them after a cross-repo pass". Read
 * from the workflows, it stays uncomfortable until someone schedules them.
 *
 * ONLY TRACKED TOOLS ARE LISTED. A file in tools/ that git does not track is work in
 * progress, and publishing it as fleet machinery would invite someone to run it. The
 * table says so in a footnote rather than leaving its absence to be read as a claim
 * that nothing else exists.
 *
 * Usage (from the repo root):
 *   node tools/tools-sync.js          rewrite the block in README.md
 *   node tools/tools-sync.js check    exit 1 if the block is out of step, or if a
 *                                     tracked tool is missing Run:/Prevents:
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const TOOLS = __dirname;
const README = path.join(ROOT, 'README.md');
const WORKFLOWS = path.join(ROOT, '.github', 'workflows');
const BEGIN = '<!-- tools-sync:begin — generated by tools/tools-sync.js from each tool\'s own header; do not edit by hand -->';
const END = '<!-- tools-sync:end -->';

const errors = [];
const fail = (m) => errors.push(m);

/** Tools git tracks. An untracked file is work in progress, not fleet machinery. */
function tracked() {
  const out = execFileSync('git', ['ls-files', '--', 'tools'], { cwd: ROOT, encoding: 'utf8' });
  return new Set(out.split('\n').filter(Boolean).map((p) => path.basename(p)));
}

/** The header block: everything before the first line of code. */
function header(text) {
  const lines = [];
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (t.startsWith('#!')) continue;
    if (t.startsWith('/*') || t.startsWith('*') || t.startsWith('//')) {
      lines.push(t.replace(/^\/\*+/, '').replace(/^\*+\/?/, '').replace(/^\/\//, '').trim());
      continue;
    }
    if (!t) { lines.push(''); continue; }
    break;
  }
  return lines;
}

function readTool(file) {
  const lines = header(fs.readFileSync(path.join(TOOLS, file), 'utf8'));
  const tagged = (tag) => {
    /* Case-sensitive and space-terminated on purpose: transform.mjs quotes YAML in
       its header, and a loose match read that file's `run: |` as this tag. */
    const i = lines.findIndex((l) => l.startsWith(`${tag}: `));
    if (i < 0) return null;
    /* One line, deliberately. Letting it wrap meant reading whatever prose followed:
       readme-sync's and teach-layout's rows each swallowed their usage blocks. A
       sentence too long for one line is a sentence worth shortening. */
    return lines[i].slice(tag.length + 1).trim();
  };

  /* The purpose is the first sentence after the "name.js — " opener. */
  const opener = lines.find((l) => l.startsWith(`${file} —`)) || '';
  let purpose = opener.slice(`${file} —`.length).trim();
  for (let i = lines.indexOf(opener) + 1; i < lines.length && purpose && !/[.!?]$/.test(purpose); i += 1) {
    if (!lines[i] || /^[A-Za-z][\w -]*:/.test(lines[i])) break;
    purpose += ` ${lines[i]}`;
  }
  return {
    file,
    purpose: purpose.replace(/\s+/g, ' ').trim(),
    run: tagged('Run'),
    prevents: tagged('Prevents'),
    reads: tagged('Reads'),
  };
}

/** Which workflow, if any, runs this tool — and on what triggers. */
/* Which workflow job runs this tool, and when that JOB runs.
 *
 * Per job, not per workflow: teach.yml is triggered by pull_request, push AND a daily
 * cron, but its check and layout jobs are gated to the first two and its drift job to
 * the last. Reading the workflow's triggers gave every tool in the file all three, so
 * teach-drift read "every PR and push" when it only ever runs daily — a wrong cadence
 * published in the table whose whole purpose is the cadence. */
function cadence({workflows = WORKFLOWS, tools = TOOLS} = {}) {
  const byTool = new Map();
  const selftests = new Map();
  byTool.selftests = selftests;
  if (!fs.existsSync(workflows)) return byTool;
  for (const wf of fs.readdirSync(workflows).filter((f) => /\.ya?ml$/.test(f))) {
    const text = fs.readFileSync(path.join(workflows, wf), 'utf8');
    const on = /^on:([\s\S]*?)^\w/m.exec(text);
    const trig = on ? on[1] : '';
    const event = name => {
      const m = new RegExp(`^ {2}${name}:([^]*?)(?=^ {2}\\w+:|(?![^]))`, 'm').exec(trig);
      return m ? { present: true, filtered: /^ {4}(paths|paths-ignore):/m.test(m[1]) } : { present: false };
    };
    const pr = event('pull_request'), push = event('push');
    const hasDispatch = /^ {2}workflow_dispatch:/m.test(trig);
    /* A cron is not automatically "daily". `41 7 * * 1` runs on Mondays, and calling
       that daily in the table would be the same class of error as the per-workflow
       cadence bug: a number read from the right place and reported as the wrong fact. */
    const crons = [...trig.matchAll(/cron:\s*'([^']+)'/g)].map((m) => m[1]);
    const cronWord = (expr) => {
      const [, , dom, mon, dow] = expr.trim().split(/\s+/);
      if (dow && dow !== '*') return 'weekly';
      if (dom && dom !== '*') return 'monthly';
      if (mon && mon !== '*') return 'yearly';
      return 'daily';
    };
    const cronWords = [...new Set(crons.map(cronWord))];
    const hasCron = cronWords.length > 0;

    /* Split the file into job blocks: `jobs:` then two-space-indented keys. */
    const jobsAt = text.indexOf('\njobs:');
    if (jobsAt < 0) continue;
    const body = text.slice(jobsAt);
    const starts = [...body.matchAll(/^ {2}([\w-]+):\s*$/gm)];
    for (let k = 0; k < starts.length; k += 1) {
      const from = starts[k].index;
      const to = k + 1 < starts.length ? starts[k + 1].index : body.length;
      const job = body.slice(from, to);
      const cond = /^ {4}if:\s*(.+)$/m.exec(job);
      const gate = cond ? cond[1] : '';
      const words = new Set();
      const gatedToSchedule = /schedule|workflow_dispatch/.test(gate) && !/pull_request|push/.test(gate);
      const gatedToPR = /pull_request|push/.test(gate) && !/schedule/.test(gate);
      if (!gatedToSchedule) {
        if (pr.present && push.present && !pr.filtered && !push.filtered) words.add('every PR and push');
        else {
          if (pr.present) words.add(pr.filtered ? 'selected PRs' : 'every PR');
          if (push.present) words.add(push.filtered ? 'selected pushes' : 'every push');
        }
      }
      if (hasCron && !gatedToPR) cronWords.forEach((w) => words.add(w));
      if (hasDispatch && !gatedToPR) words.add('on demand');
      /* Comments do not run. This workflow carries a block explaining what
         protection-census would need to be scheduled, quoting the step that would run
         it — and counting that as an invocation put the tool back in the table as
         weekly, which is precisely the claim the block exists to say is not true. */
      const executable = job.split('\n').filter((l) => !/^\s*#/.test(l)).join('\n');
      for (const m of executable.matchAll(/node (tools\/[\w.-]+)([^\n]*)/g)) {
        const name = path.basename(m[1]);
        // A fixture invocation does not run the tool's fleet/check mode and
        // must not propagate that cadence to its normal CLI subprocesses.
        const target = /^\s+(?:selftest|--check-fixtures)(?:\s|$)/.test(m[2]) ? selftests : byTool;
        const said = target.get(name) || new Set();
        words.forEach((w) => said.add(w));
        target.set(name, said);
      }
    }
  }

  /* A checker a SCHEDULED tool runs is scheduled. fleet-check.js is the only thing the
     weekly workflow names, and it runs six others; without following that hop the six
     would still read "manual" in a table whose whole subject is what runs unattended.
     Only executable references count — comments are stripped first, because half these
     headers name each other in prose. */
  const code = (file) => fs.readFileSync(path.join(tools, file), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split('\n').filter((l) => !l.trim().startsWith('//')).join('\n');
  let changed = true;
  while (changed) {
    changed = false;
    for (const [caller, words] of [...byTool]) {
      if (!words.size) continue;
      let src;
      try { src = code(caller); } catch { continue; }
      /* Normal quotes only, NOT backticks. A backtick-delimited `tools/x.js` is
         markdown formatting, and catalog-sync.js generates prose full of it —
         which had catalog-evidence.js, a weekly clone-backed checker, reported
         as running on every PR and push. Same error as the YAML comments above:
         a tool NAMED by another tool is not a tool RUN by it. */
      for (const m of src.matchAll(/['"]tools\/([\w.-]+)['"]/g)) {
        const callee = m[1];
        if (callee === caller) continue;
        const have = byTool.get(callee) || new Set();
        const before = have.size;
        words.forEach((w) => have.add(w));
        if (have.size !== before) { byTool.set(callee, have); changed = true; }
      }
    }
  }
  return byTool;
}

function rows() {
  const keep = tracked();
  const files = fs.readdirSync(TOOLS)
    .filter((f) => /\.(js|mjs)$/.test(f))
    .filter((f) => keep.has(f))
    .sort();
  const when = cadence();
  const listed = [];
  const notRun = [];
  for (const file of files) {
    const t = readTool(file);
    if (!t.run && !t.prevents) { notRun.push(file); continue; }
    if (!t.run) fail(`${file}: has a "Prevents:" line but no "Run:" line`);
    if (!t.prevents) fail(`${file}: is runnable but its header does not say what failure it prevents — add a "Prevents:" line`);
    /* A tool must name its SOURCES as well as its purpose. Four times a checker
       here has answered from something near the question rather than the thing
       the question is about - one protection endpoint instead of two, the
       TypeScript in a Rust lab, a missing clone, an unfetched one - and each
       time the bug was one line under logic that was sound, which is why
       reviewing the logic never found it. The first step on any new or changed
       checker is to print the source it opened for one subject and confirm by
       hand that it is the thing the checker claims to describe. This line is
       what that reader checks against, so it is required. */
    if (!t.reads) fail(`${file}: is runnable but its header does not say what it opens — add a "Reads:" line naming the exact paths, endpoints, refs or commands`);
    const said = [...(when.get(file) || [])];
    const fixtures = [...(when.selftests.get(file) || [])];
    listed.push({ ...t, manual: !said.length, when: (said.length ? said.join(', ') : 'manual')
      + (fixtures.length ? '; selftest only: ' + fixtures.join(', ') : '') });
  }
  return { listed, notRun, untracked: fs.readdirSync(TOOLS).filter((f) => /\.(js|mjs)$/.test(f) && !keep.has(f)).sort() };
}

function block() {
  const { listed, notRun, untracked } = rows();
  const esc = (s) => String(s).replace(/\|/g, '\\|');
  const out = [BEGIN, ''];
  out.push('| Tool | What it prevents | When it runs |');
  out.push('|---|---|---|');
  for (const t of listed) {
    out.push(`| \`${esc(t.run)}\` | ${esc(t.prevents)} | ${esc(t.when)} |`);
  }
  out.push('');
  const manual = listed.filter((t) => t.manual).length;
  out.push(`${manual} of these ${listed.length} listed commands run only when someone runs them. The rest run in CI, on the `
    + 'cadence shown. Selftest-only runs exercise fixtures, not the live fleet. A checker nobody runs reports nothing, which is the failure every one of these was written after.');
  if (notRun.length) {
    out.push('');
    out.push(`Not listed above: ${notRun.map((f) => `\`${f}\``).join(', ')} — support code, fixtures, and `
      + 'one-off rewriters kept as the precise record of what was done to the fleet rather than as things to run.');
  }
  /* A CONSTANT sentence, with no filenames in it.
   *
   * Naming the untracked files made the generated block depend on the working
   * tree of whoever ran it: CI checks out tracked files only, so it regenerates
   * a block with no footnote and fails against a README committed from a machine
   * that had work in progress in `tools/`. A generated file that cannot be
   * reproduced from the repository is not generated, it is transcribed.
   *
   * The sentence still does the job it was added for - an absence here must not
   * read as a claim that nothing else exists - and the actual filenames go to
   * stdout, where the person running it is the one who can see them anyway. */
  out.push('');
  out.push('This table lists the tools git tracks. Anything untracked in `tools/` is work in '
    + 'progress rather than fleet machinery, and is absent here for that reason rather than '
    + 'because nothing else exists.');
  out.push('');
  out.push(END);
  return out.join('\n');
}

function main() {
  const mode = process.argv[2];
  const readme = fs.readFileSync(README, 'utf8');
  const next = block();
  if (errors.length) {
    for (const e of errors) console.error(`ERROR ${e}`);
    process.exit(1);
  }
  const has = readme.includes(BEGIN) && readme.includes(END);
  if (!has) {
    if (mode === 'check') {
      console.error(`ERROR README.md has no tools-sync block. Run: node tools/tools-sync.js`);
      process.exit(1);
    }
    fs.writeFileSync(README, `${readme.replace(/\s*$/, '')}\n\n${next}\n`);
    console.log('README.md: tools block added.');
    return;
  }
  const current = readme.slice(readme.indexOf(BEGIN), readme.indexOf(END) + END.length);
  if (current === next) {
    console.log(`README.md tools block in step with tools/ (${next.split('\n').filter((l) => l.startsWith('| `')).length} tools listed).`);
    return;
  }
  if (mode === 'check') {
    console.error('OUT OF DATE README.md tools block');
    console.error('Run: node tools/tools-sync.js   (then commit the result; never hand-edit the block)');
    process.exit(1);
  }
  fs.writeFileSync(README, readme.replace(current, next));
  console.log('README.md tools block regenerated.');
  const loose = rows().untracked;
  if (loose.length) console.log(`  untracked in tools/, deliberately not listed in the table: ${loose.join(', ')}`);
}

module.exports = {cadence};
if (require.main === module) main();
